export const types_user = {
    USER_ADD: 'USER_ADD',
    USER_FIND_ONE: 'USER_FIND_ONE',
    CINE_REQUEST: 'CINE_REQUEST',
    DELETE_CINE_REQUEST: 'DELETE_CINE_REQUEST',
    FIND_CINE_REQUEST: 'FIND_CINE_REQUEST'
}